# CS 4660 - Lab 1
### Chelle Cruz

### 1. Import the numpy package with the alias np

In [1]:
import numpy as np

### 2. Create a vector of zeros of size 10 but the fifth value which is 1 

In [2]:
zeroes = np.zeros(10, dtype=int)
zeroes[4] = 1
print(zeroes)


[0 0 0 0 1 0 0 0 0 0]


### 3. Create a 3 X 3 array of any values. Add a column of ones to the end

In [3]:
a = np.arange(10, 19).reshape((3,3))
a[:, -1:] = 1
print(a)

[[10 11  1]
 [13 14  1]
 [16 17  1]]


### 4. Create a vector with values ranging from 10 to 49 

In [4]:
b = np.arange(10, 50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5. Reverse the above vector (first element becomes last)

In [5]:
b = b[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 6. Create a 4x4 matrix with values ranging from 0 to 15 

In [6]:
c = np.arange(16).reshape((4,4))
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### 7. Create a 3x3x3 array with random values 

In [7]:
d = np.floor(50 * np.random.random((3,3,3))).astype(int)
print(d)

[[[ 1 17  4]
  [ 9 27  8]
  [ 7 43 12]]

 [[45 21 24]
  [30 18 32]
  [32 16 23]]

 [[ 9 31 18]
  [38 22 40]
  [ 0  7 16]]]


### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [8]:
random_array = np.floor(50 * np.random.random((10,10))).astype(int)
print(random_array)
print("Min:", random_array.min())
print("Max:", random_array.max())

[[ 4  8 35  3 45  1 37 35 18 17]
 [39 43  9 46 41 18 28 46  3 12]
 [45 21 15  6 20 45 45 43  2 16]
 [24 27 23 46 13  8 41 35  8  7]
 [ 6  4 28 48 15 29 44 48 37 41]
 [30 43 10 44 41 44  1 25 13 27]
 [17 42 22 46  5 46 22 45 19  7]
 [26  9  1 18 27 31 42 25 29 24]
 [41  0  3 43 16 44 37 19 17 44]
 [10 49 47 34 41  7  7 17 13 47]]
Min: 0
Max: 49


### 9. Create a random vector of size 30 and find the mean value 

In [9]:
e = np.floor(50 * np.random.random((30,))).astype(int)
print(e)
print("Mean:", np.mean(e))

[30 28  5 31 44  2  3 16 45  4 47  9  1 35  5 46 30 35 41  3 27 29 41 25  1
 45 36 21 28 43]
Mean: 25.2


### 10. What does NaN mean? Submit in a comment

NaN = not a number

### 11. Write a function that takes 1D array and negates all elements which are between 3 and 8, in place. Demo it with an array of your choosing

In [10]:
# Negate elements between 3 and 8 on array
def negate(array):
    array[(3 <= array) & (array <= 8)] *= -1

negate(e)
print(e)


[30 28 -5 31 44  2 -3 16 45 -4 47  9  1 35 -5 46 30 35 41 -3 27 29 41 25  1
 45 36 21 28 43]
